### ISSUE TITLE
Non-breaking hyphens when not stretching words

### ISSUE THREAD

**Issue by Gragt** [iesegnu/dorothy-m-richardson_pointed-roofs#1]
Many spoken words are broken with hyphens to replicate speech. Most of these in the production use non-breaking hyphens to show the sound is being stretched, but some hyphens appear to indicate a pause. For example, *a-coming* (Chapter 1, line 147) and *Bair-ta* (Chapter 10, line 73) do not appear to stretch the word, but *sh‑ham‑poo* (Chapter 3, line 187) and *glooo‑om* (Chapter 4, line 32) do look like the sounds are stretched. You might want to review those and decide which one fits best. Do note that `typogrify` will change all those non-breaking hyphens into regular hyphens.

**Comment by iesegnu** [comment]
Thanks! I changed "a-coming", but "Bair-ta" I'd say is stretched to indicate the stress on the last syllable if pronounced in a French manner.

**Comment by Gragt** [comment]
Just to be sure: have you check all words with non-breaking hyphens in your production to see that they were needed? Those I gave were just examples.

Well, I would add a pause when saying that sentence from a French perspective, but I admit this is rather subjective. It is one of those things where we have to use our best judgement. The only thing to keep in mind, though, is that we are trying to make it easy for the reader to access the content while respecting the author’s voice: they shouldn’t have to fight with archaisms nor technological constraints.

In this case, a non-breaking hyphen will help the reader see that the sound is being stretched because these parts will stay together, unlike a regular hyphen that can allow the rest of the word to be sent to the next line, but too many of them in short intervals for sounds that may not be stretched may cause rendering issues—and during the review I wondered if the hyphens didn’t alternate at times between pauses and stretches within the same words.

Due to the subjective nature of the task, and the fact that you have spent more hours on this book than me, I leave it up to you. If you tell me that you have checked all non-breaking hyphens and that they each reasonably represent sound being stretched, that’s good enough. If anything, SE books are “living” books and can always be revisited later.

**Comment by iesegnu** [comment]
I had another look at the non-breaking hyphens and changed these to normal ones: "Là-là-Boum-Bong" (ch. 3, l. 125), "Oh-là-là!" (ch. 3, l. 220), and "beem-beem" (ch. 6, l. 142).

In "Nun⁠—dank⁠—et⁠—Al⁠—le⁠—Gott" and "Now⁠—thank⁠—all⁠—God", I reinstated the original em dashes. Upon review, it looks to me like there is no speech at all here and the lines are only mentally scanned by the character and the syllables broken apart (unless that would also be a case for breaking hyphens?).

For "Bair-ta", I'm not sure. The line is written in English but said in French according to the narrator, so it's difficult to know what the actual function of the hyphen is. But since this is at the beginning of the paragraph, I doubt that it will ever be displayed over two lines, even with a breaking hyphen.

**Comment by Gragt** [comment]
It is difficult to say with some authors. There isn’t much more to do than use your best judgement. If needed, compare the original scans, decide what the hyphens and dashes are supposed to mean, and go with it.

**Comment by iesegnu** [comment]
Thanks, I'll do it like this then.
